CREATE TABLE USUARIO (
    ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CPF NUMBER(11) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CRIADOR (
    ID_USUARIO NUMBER NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE PARTICIPANTE (
    ID_USUARIO NUMBER NOT NULL,
    PRIMARY KEY (ID_USUARIO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE EVENTO (
    ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_EVENTO DATE NOT NULL,
    LOCAL VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(500),
    ID_CRIADOR NUMBER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CRIADOR) REFERENCES CRIADOR(ID_USUARIO)
);

CREATE TABLE SUBEVENTO (
    ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(500),
    LOCAL VARCHAR2(100) NOT NULL,
    DATA_EVENTO DATE NOT NULL,
    ID_EVENTO NUMBER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID)
);

CREATE TABLE SESSAO (
    ID NUMBER NOT NULL,
    HORA_TERMINO TIMESTAMP NOT NULL,
    HORA_INICIO TIMESTAMP NOT NULL,
    DESCRICAO VARCHAR2(500),
    DATA_EVENTO DATE NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SESSAO_EVENTO (
    ID_SESSAO NUMBER NOT NULL,
    ID_EVENTO NUMBER NOT NULL,
    PRIMARY KEY (ID_SESSAO, ID_EVENTO),
    FOREIGN KEY (ID_SESSAO) REFERENCES SESSAO(ID),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID)
);

CREATE TABLE SESSAO_SUBEVENTO (
    ID_SESSAO NUMBER NOT NULL,
    ID_SUBEVENTO NUMBER NOT NULL,
    PRIMARY KEY (ID_SESSAO, ID_SUBEVENTO),
    FOREIGN KEY (ID_SESSAO) REFERENCES SESSAO(ID),
    FOREIGN KEY (ID_SUBEVENTO) REFERENCES SUBEVENTO(ID)
);

CREATE TABLE EMAIL (
    ID_USUARIO NUMBER NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PRIMARY KEY (ID_USUARIO, EMAIL),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE PARTICIPACAO (
    ID_PARTICIPANTE NUMBER NOT NULL,
    ID_EVENTO NUMBER NOT NULL,
    PRIMARY KEY (ID_PARTICIPANTE, ID_EVENTO),
    FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTE(ID_USUARIO),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID)
);

CREATE TABLE CERTIFICADO (
    ID NUMBER NOT NULL,
    ID_EVENTO NUMBER NOT NULL,
    ID_PARTICIPANTE NUMBER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID),
    FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTE(ID_USUARIO)
);

CREATE TABLE EMITE (
    ID_EVENTO NUMBER NOT NULL,
    ID_PARTICIPANTE NUMBER NOT NULL,
    ID_CERTIFICADO NUMBER NOT NULL,
    PRIMARY KEY (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID),
    FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTE(ID_USUARIO),
    FOREIGN KEY (ID_CERTIFICADO) REFERENCES CERTIFICADO(ID)
);

INSERT ALL
    INTO USUARIO (ID, NOME, CPF) VALUES (1, 'Alice Silva', 12345678901)
    INTO USUARIO (ID, NOME, CPF) VALUES (2, 'João Pereira', 98765432109)
    INTO USUARIO (ID, NOME, CPF) VALUES (3, 'Maria Santos', 11122233344)
    INTO USUARIO (ID, NOME, CPF) VALUES (4, 'Carlos Lima', 55566677788)
    INTO USUARIO (ID, NOME, CPF) VALUES (5, 'Ana Costa', 99988877766)
    INTO USUARIO (ID, NOME, CPF) VALUES (6, 'Lucas Alves', 10101010101)
    INTO USUARIO (ID, NOME, CPF) VALUES (7, 'Fernanda Oliveira', 20202020202)
    INTO USUARIO (ID, NOME, CPF) VALUES (8, 'Bruno Souza', 30303030303)
    INTO USUARIO (ID, NOME, CPF) VALUES (9, 'Carla Ferreira', 40404040404)
    INTO USUARIO (ID, NOME, CPF) VALUES (10, 'Paulo Mendes', 50505050505)
    INTO USUARIO (ID, NOME, CPF) VALUES (11, 'Camila Rocha', 60606060606)
    INTO USUARIO (ID, NOME, CPF) VALUES (12, 'Renato Martins', 70707070707)
    INTO USUARIO (ID, NOME, CPF) VALUES (13, 'Júlia Carvalho', 80808080808)
    INTO USUARIO (ID, NOME, CPF) VALUES (14, 'Eduardo Araújo', 90909090909)
    INTO USUARIO (ID, NOME, CPF) VALUES (15, 'Beatriz Cunha', 12312312312)
    INTO USUARIO (ID, NOME, CPF) VALUES (16, 'Diego Barros', 32132132132)
    INTO USUARIO (ID, NOME, CPF) VALUES (17, 'Natália Ramos', 45645645645)
    INTO USUARIO (ID, NOME, CPF) VALUES (18, 'Rafael Nogueira', 65465465465)
    INTO USUARIO (ID, NOME, CPF) VALUES (19, 'Vanessa Lima', 78978978978)
    INTO USUARIO (ID, NOME, CPF) VALUES (20, 'André Borges', 98798798798)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO CRIADOR (ID_USUARIO) VALUES (1)
    INTO CRIADOR (ID_USUARIO) VALUES (2)
    INTO CRIADOR (ID_USUARIO) VALUES (3)
    INTO CRIADOR (ID_USUARIO) VALUES (4)
    INTO CRIADOR (ID_USUARIO) VALUES (5)
    INTO CRIADOR (ID_USUARIO) VALUES (6)
    INTO CRIADOR (ID_USUARIO) VALUES (7)
    INTO CRIADOR (ID_USUARIO) VALUES (8)
    INTO CRIADOR (ID_USUARIO) VALUES (9)
    INTO CRIADOR (ID_USUARIO) VALUES (10)
    INTO CRIADOR (ID_USUARIO) VALUES (11)
    INTO CRIADOR (ID_USUARIO) VALUES (12)
    INTO CRIADOR (ID_USUARIO) VALUES (13)
    INTO CRIADOR (ID_USUARIO) VALUES (14)
    INTO CRIADOR (ID_USUARIO) VALUES (15)
    INTO CRIADOR (ID_USUARIO) VALUES (16)
    INTO CRIADOR (ID_USUARIO) VALUES (17)
    INTO CRIADOR (ID_USUARIO) VALUES (18)
    INTO CRIADOR (ID_USUARIO) VALUES (19)
    INTO CRIADOR (ID_USUARIO) VALUES (20)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO PARTICIPANTE (ID_USUARIO) VALUES (11)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (12)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (13)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (14)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (15)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (16)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (17)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (18)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (19)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (20)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (1)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (2)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (3)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (4)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (5)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (6)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (7)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (8)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (9)
    INTO PARTICIPANTE (ID_USUARIO) VALUES (10)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (1, 'Conferência de Tecnologia', DATE '2024-01-10', 'São Paulo', 'Evento sobre inovação tecnológica.', 1)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (2, 'Feira de Saúde', DATE '2024-02-20', 'Rio de Janeiro', 'Ações para promover saúde pública.', 2)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (3, 'Workshop de Fotografia', DATE '2024-03-15', 'Curitiba', 'Aulas práticas para fotógrafos.', 3)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (4, 'Seminário de Educação', DATE '2024-04-05', 'Recife', 'Discussões sobre o ensino no Brasil.', 4)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (5, 'Encontro de Negócios', DATE '2024-05-22', 'Brasília', 'Conexões empresariais e startups.', 5)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (6, 'Congresso de Medicina', DATE '2024-06-11', 'Salvador', 'Pesquisas na área médica.', 6)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (7, 'Festival de Música', DATE '2024-07-08', 'Fortaleza', 'Apresentações de artistas independentes.', 7)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (8, 'Hackathon', DATE '2024-08-14', 'São Paulo', 'Competição de programação.', 8)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (9, 'Simpósio de Literatura', DATE '2024-09-01', 'Porto Alegre', 'Discussões sobre literatura moderna.', 9)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (10, 'Maratona de Matemática', DATE '2024-10-25', 'Florianópolis', 'Competições para estudantes.', 10)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (11, 'Curso de Design', DATE '2024-01-20', 'Belo Horizonte', 'Práticas de design gráfico.', 11)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (12, 'Congresso Jurídico', DATE '2024-02-15', 'Belém', 'Novas jurisprudências.', 12)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (13, 'Palestra de Liderança', DATE '2024-03-10', 'Natal', 'Como liderar com eficiência.', 13)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (14, 'Encontro de Astronomia', DATE '2024-04-18', 'Manaus', 'Novos estudos sobre o universo.', 14)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (15, 'Feira de Robótica', DATE '2024-05-29', 'São Paulo', 'Inovações na robótica.', 15)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (16, 'Workshop de Artes', DATE '2024-06-20', 'Rio de Janeiro', 'Técnicas de pintura e escultura.', 16)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (17, 'Evento Gastronômico', DATE '2024-07-22', 'Fortaleza', 'Apreciação da culinária regional.', 17)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (18, 'Encontro de História', DATE '2024-08-05', 'Recife', 'Estudos históricos.', 18)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (19, 'Festival de Cinema', DATE '2024-09-10', 'Curitiba', 'Mostras de filmes independentes.', 19)
    INTO EVENTO (ID, NOME, DATA_EVENTO, LOCAL, DESCRICAO, ID_CRIADOR) 
    VALUES (20, 'Congresso de TI', DATE '2024-10-12', 'São Paulo', 'Novas tendências em tecnologia.', 20)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (1, 'Palestra de Inovação', 'Discussão sobre inovações tecnológicas.', 'Sala 101', DATE '2024-01-10', 1)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (2, 'Palestra de Saúde', 'Tópicos sobre saúde pública.', 'Sala 102', DATE '2024-02-20', 2)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (3, 'Workshop de Fotografia Digital', 'Aulas práticas sobre fotografia digital.', 'Sala 201', DATE '2024-03-15', 3)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (4, 'Mesa-redonda sobre Educação', 'Discussões sobre metodologias educacionais.', 'Auditório', DATE '2024-04-05', 4)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (5, 'Painel de Startups', 'Apresentações de novos negócios.', 'Auditório', DATE '2024-05-22', 5)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (6, 'Seminário sobre Medicina', 'Discussões sobre novas descobertas médicas.', 'Auditório', DATE '2024-06-11', 6)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (7, 'Show de Bandas Locais', 'Apresentação de bandas independentes.', 'Palco Principal', DATE '2024-07-08', 7)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (8, 'Competição de Programação', 'Desafios e competições de programação.', 'Sala 103', DATE '2024-08-14', 8)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (9, 'Leitura e Discussão de Livros', 'Discussões sobre obras literárias contemporâneas.', 'Sala 104', DATE '2024-09-01', 9)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (10, 'Competição de Matemática', 'Desafio matemático para jovens talentos.', 'Sala 105', DATE '2024-10-25', 10)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (11, 'Workshop de Design Gráfico', 'Técnicas avançadas de design digital.', 'Sala 106', DATE '2024-01-20', 11)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (12, 'Palestra sobre Direito', 'Abordagem das leis atuais e jurisprudência.', 'Auditório', DATE '2024-02-15', 12)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (13, 'Palestra de Liderança e Gestão', 'Como gerenciar equipes de sucesso.', 'Sala 107', DATE '2024-03-10', 13)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (14, 'Observação Astronômica', 'Observações de estrelas e planetas.', 'Observatório', DATE '2024-04-18', 14)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (15, 'Exposição de Robótica', 'Demonstração de projetos de robótica.', 'Sala 108', DATE '2024-05-29', 15)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (16, 'Workshop de Pintura', 'Aulas práticas sobre técnicas de pintura.', 'Sala 109', DATE '2024-06-20', 16)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (17, 'Aula de Culinária Regional', 'Preparação de pratos típicos locais.', 'Cozinha Experimental', DATE '2024-07-22', 17)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (18, 'Palestra sobre História Contemporânea', 'Análise de eventos históricos recentes.', 'Auditório', DATE '2024-08-05', 18)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (19, 'Exibição de Filmes Independentes', 'Mostra de curtas e longas metragens independentes.', 'Sala de Cinema', DATE '2024-09-10', 19)
    INTO SUBEVENTO (ID, NOME, DESCRICAO, LOCAL, DATA_EVENTO, ID_EVENTO)
    VALUES (20, 'Seminário de Tendências em TI', 'Novas tecnologias e inovações na área de TI.', 'Auditório', DATE '2024-10-12', 20)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (1, TIMESTAMP '2024-01-10 09:00:00', TIMESTAMP '2024-01-10 10:30:00', 'Abertura do evento e introdução aos temas.', DATE '2024-01-10', 'Sessão de Abertura')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (2, TIMESTAMP '2024-01-10 11:00:00', TIMESTAMP '2024-01-10 12:30:00', 'Palestra sobre novas tecnologias.', DATE '2024-01-10', 'Palestra de Inovação')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (3, TIMESTAMP '2024-02-20 14:00:00', TIMESTAMP '2024-02-20 15:30:00', 'Discussão sobre o impacto da saúde pública.', DATE '2024-02-20', 'Palestra de Saúde')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (4, TIMESTAMP '2024-03-15 10:00:00', TIMESTAMP '2024-03-15 11:30:00', 'Workshop sobre fotografia digital.', DATE '2024-03-15', 'Workshop de Fotografia Digital')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (5, TIMESTAMP '2024-04-05 13:00:00', TIMESTAMP '2024-04-05 14:30:00', 'Análise de metodologias educacionais.', DATE '2024-04-05', 'Mesa-redonda sobre Educação')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (6, TIMESTAMP '2024-05-22 15:00:00', TIMESTAMP '2024-05-22 16:30:00', 'Discussão sobre novos modelos de negócios.', DATE '2024-05-22', 'Painel de Startups')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (7, TIMESTAMP '2024-06-11 09:00:00', TIMESTAMP '2024-06-11 10:30:00', 'Debate sobre descobertas recentes na medicina.', DATE '2024-06-11', 'Seminário sobre Medicina')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (8, TIMESTAMP '2024-07-08 11:00:00', TIMESTAMP '2024-07-08 12:30:00', 'Show com bandas locais.', DATE '2024-07-08', 'Show de Bandas Locais')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (9, TIMESTAMP '2024-08-14 14:00:00', TIMESTAMP '2024-08-14 15:30:00', 'Competição de programação entre equipes.', DATE '2024-08-14', 'Competição de Programação')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (10, TIMESTAMP '2024-09-01 10:00:00', TIMESTAMP '2024-09-01 11:30:00', 'Discussão sobre literatura moderna e autores contemporâneos.', DATE '2024-09-01', 'Leitura e Discussão de Livros')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (11, TIMESTAMP '2024-10-25 09:00:00', TIMESTAMP '2024-10-25 10:30:00', 'Desafio matemático para estudantes.', DATE '2024-10-25', 'Competição de Matemática')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (12, TIMESTAMP '2024-01-20 13:00:00', TIMESTAMP '2024-01-20 14:30:00', 'Aulas de design gráfico para iniciantes.', DATE '2024-01-20', 'Workshop de Design Gráfico')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (13, TIMESTAMP '2024-02-15 11:00:00', TIMESTAMP '2024-02-15 12:30:00', 'Debate sobre as novas leis no direito brasileiro.', DATE '2024-02-15', 'Palestra sobre Direito')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (14, TIMESTAMP '2024-03-10 10:00:00', TIMESTAMP '2024-03-10 11:30:00', 'Como ser um líder eficaz no mercado corporativo.', DATE '2024-03-10', 'Palestra de Liderança e Gestão')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (15, TIMESTAMP '2024-04-18 14:00:00', TIMESTAMP '2024-04-18 15:30:00', 'Observações astronômicas ao vivo.', DATE '2024-04-18', 'Observação Astronômica')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (16, TIMESTAMP '2024-05-29 11:00:00', TIMESTAMP '2024-05-29 12:30:00', 'Exibição de robôs e tecnologias inovadoras.', DATE '2024-05-29', 'Exposição de Robótica')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (17, TIMESTAMP '2024-06-20 13:00:00', TIMESTAMP '2024-06-20 14:30:00', 'Workshop sobre técnicas de pintura.', DATE '2024-06-20', 'Workshop de Pintura')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (18, TIMESTAMP '2024-07-22 10:00:00', TIMESTAMP '2024-07-22 11:30:00', 'Demonstração culinária de pratos típicos locais.', DATE '2024-07-22', 'Aula de Culinária Regional')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (19, TIMESTAMP '2024-08-05 14:00:00', TIMESTAMP '2024-08-05 15:30:00', 'Discussão sobre eventos históricos recentes.', DATE '2024-08-05', 'Palestra sobre História Contemporânea')
    INTO SESSAO (ID, HORA_INICIO, HORA_TERMINO, DESCRICAO, DATA_EVENTO, NOME)
    VALUES (20, TIMESTAMP '2024-10-12 11:00:00', TIMESTAMP '2024-10-12 12:30:00', 'Apresentação de novas tecnologias na área de TI.', DATE '2024-10-12', 'Seminário de Tendências em TI')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (1, 1)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (2, 1)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (3, 2)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (4, 3)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (5, 4)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (6, 5)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (7, 6)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (8, 7)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (9, 8)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (10, 9)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (11, 10)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (12, 11)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (13, 12)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (14, 13)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (15, 14)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (16, 15)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (17, 16)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (18, 17)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (19, 18)
    INTO SESSAO_EVENTO (ID_SESSAO, ID_EVENTO)
    VALUES (20, 19)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (1, 1)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (2, 2)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (3, 3)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (4, 4)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (5, 5)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (6, 6)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (7, 7)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (8, 8)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (9, 9)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (10, 10)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (11, 11)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (12, 12)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (13, 13)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (14, 14)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (15, 15)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (16, 16)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (17, 17)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (18, 18)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (19, 19)
    INTO SESSAO_SUBEVENTO (ID_SESSAO, ID_SUBEVENTO) VALUES (20, 20)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (1, 'alice.silva@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (2, 'joao.pereira@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (3, 'maria.santos@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (4, 'carlos.lima@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (5, 'ana.costa@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (6, 'lucas.alves@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (7, 'fernanda.oliveira@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (8, 'bruno.souza@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (9, 'carla.ferreira@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (10, 'paulo.mendes@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (11, 'camila.rocha@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (12, 'renato.martins@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (13, 'julia.carvalho@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (14, 'eduardo.araujo@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (15, 'beatriz.cunha@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (16, 'diego.barros@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (17, 'natalia.ramos@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (18, 'rafael.nogueira@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (19, 'vanessa.lima@email.com')
    INTO EMAIL (ID_USUARIO, EMAIL) VALUES (20, 'andre.borges@email.com')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (1, 1)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (2, 1)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (3, 2)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (4, 3)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (5, 4)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (6, 5)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (7, 6)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (8, 7)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (9, 8)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (10, 9)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (11, 10)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (12, 11)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (13, 12)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (14, 13)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (15, 14)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (16, 15)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (17, 16)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (18, 17)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (19, 18)
    INTO PARTICIPACAO (ID_PARTICIPANTE, ID_EVENTO) VALUES (20, 19)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (1, 1, 1)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (2, 1, 2)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (3, 2, 3)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (4, 3, 4)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (5, 4, 5)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (6, 5, 6)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (7, 6, 7)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (8, 7, 8)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (9, 8, 9)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (10, 9, 10)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (11, 10, 11)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (12, 11, 12)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (13, 12, 13)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (14, 13, 14)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (15, 14, 15)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (16, 15, 16)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (17, 16, 17)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (18, 17, 18)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (19, 18, 19)
    INTO CERTIFICADO (ID, ID_EVENTO, ID_PARTICIPANTE) VALUES (20, 19, 20)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (1, 1, 1)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (1, 2, 2)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (2, 3, 3)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (3, 4, 4)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (4, 5, 5)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (5, 6, 6)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (6, 7, 7)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (7, 8, 8)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (8, 9, 9)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (9, 10, 10)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (10, 11, 11)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (11, 12, 12)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (12, 13, 13)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (13, 14, 14)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (14, 15, 15)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (15, 16, 16)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (16, 17, 17)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (17, 18, 18)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (18, 19, 19)
    INTO EMITE (ID_EVENTO, ID_PARTICIPANTE, ID_CERTIFICADO) VALUES (19, 20, 20)
SELECT 1 FROM DUAL;

/*Listar todos os usuários cadastrados.*/
SELECT * FROM USUARIO;

/*Obter os nomes dos eventos.*/
SELECT NOME FROM EVENTO;

/*Exibir os subeventos associados ao evento com ID 1.*/
SELECT * FROM SUBEVENTO WHERE ID_EVENTO = 1;

/*Obter a descrição dos subeventos no evento com ID 5.*/
SELECT DESCRICAO FROM SUBEVENTO WHERE ID_EVENTO = 5;

/*Listar todos os emails cadastrados.*/
SELECT * FROM EMAIL;

/*Listar todas as sessões cadastradas.*/
SELECT * FROM SESSAO;

/*Obter os nomes dos eventos realizados na cidade de São Paulo.*/
SELECT NOME 
FROM EVENTO 
WHERE LOCAL = 'São Paulo';

/*Obter a descrição dos subeventos no evento com ID 5.*/
SELECT * 
FROM CERTIFICADO 
WHERE ID_EVENTO = 4;

/*Obter os eventos de Outubro*/
SELECT * 
FROM EVENTO 
WHERE EXTRACT(MONTH FROM DATA_EVENTO) = 10;

/*Obter as sessões com Início às 8 horas e Término às 13*/
SELECT * 
FROM SESSAO
WHERE EXTRACT(HOUR FROM HORA_INICIO) >= 8
AND EXTRACT(HOUR FROM HORA_TERMINO) <= 13;

/*Listar os Criadores dos Eventos*/
SELECT U.NOME AS CRIADOR, E.NOME AS EVENTO
FROM CRIADOR C
JOIN USUARIO U ON C.ID_USUARIO = U.ID
JOIN EVENTO E ON C.ID_USUARIO = E.ID_CRIADOR;

/*Exibir os eventos que possuem pelo menos um subevento associado*/
SELECT DISTINCT E.NOME AS EVENTO
FROM EVENTO E
JOIN SUBEVENTO S ON E.ID = S.ID_EVENTO;

/*Listar os participantes e os eventos para os quais receberam certificados.*/
SELECT U.NOME AS PARTICIPANTE, E.NOME AS EVENTO
FROM CERTIFICADO C
JOIN PARTICIPANTE P ON C.ID_PARTICIPANTE = P.ID_USUARIO
JOIN USUARIO U ON P.ID_USUARIO = U.ID
JOIN EVENTO E ON C.ID_EVENTO = E.ID;

/*Mostrar a relação entre eventos e seus subeventos.*/
SELECT E.NOME AS EVENTO, S.NOME AS SUBEVENTO
FROM EVENTO E
JOIN SUBEVENTO S ON E.ID = S.ID_EVENTO;

/*Obter eventos organizados por um criador específico*/
SELECT E.NOME 
FROM EVENTO E 
JOIN CRIADOR C ON E.ID_CRIADOR = C.ID_USUARIO
JOIN USUARIO U ON C.ID_USUARIO = U.ID
WHERE U.NOME = 'Alice Silva';

/*Obter Emails de participantes que possuem certificados.*/
SELECT DISTINCT EM.EMAIL
FROM CERTIFICADO C
JOIN PARTICIPANTE P ON C.ID_PARTICIPANTE = P.ID_USUARIO
JOIN EMAIL EM ON P.ID_USUARIO = EM.ID_USUARIO;

/*Listar a quantidade de eventos por local*/
SELECT LOCAL, COUNT(*) AS NUM_EVENTOS
FROM EVENTO
GROUP BY LOCAL;

/*Mostrar os participantes que participaram de eventos em mais de uma cidade.*/
SELECT U.NOME, COUNT(DISTINCT E.LOCAL) AS NUM_CIDADES
FROM USUARIO U
JOIN PARTICIPANTE P ON U.ID = P.ID_USUARIO
JOIN PARTICIPACAO PA ON P.ID_USUARIO = PA.ID_PARTICIPANTE
JOIN EVENTO E ON PA.ID_EVENTO = E.ID
GROUP BY U.NOME
HAVING COUNT(DISTINCT E.LOCAL) >= 1;

/*Selecionar os Eventos e seus Criadores cujo cpf comece com 123*/
SELECT E.NOME, U.NOME
FROM EVENTO E
JOIN CRIADOR C ON E.ID_CRIADOR = C.ID_USUARIO
JOIN USUARIO U ON C.ID_USUARIO = U.ID
WHERE U.CPF LIKE '123%';

/*contar quantas sessões ocorreram em Junho*/
SELECT COUNT(*) AS NUM_SESSOES 
FROM SESSAO 
WHERE EXTRACT(MONTH FROM DATA_EVENTO) = 06;

/*Selecionar a quantidade de certificados cadastrados*/
SELECT COUNT(*) AS TOTAL_CERTIFICADOS FROM CERTIFICADO;

/*listar os eventos ordenados pela quantidade de participantes*/
SELECT E.NOME AS EVENTO, COUNT(PA.ID_PARTICIPANTE) AS NUM_PARTICIPANTES
FROM EVENTO E
JOIN PARTICIPACAO PA ON E.ID = PA.ID_EVENTO
GROUP BY E.NOME
ORDER BY NUM_PARTICIPANTES DESC;

/*listar eventos com subeventos em mais de um local*/
SELECT E.NOME AS EVENTO, COUNT(DISTINCT S.LOCAL) AS NUM_LOCAIS
FROM EVENTO E
JOIN SUBEVENTO S ON E.ID = S.ID_EVENTO
GROUP BY E.NOME
HAVING COUNT(DISTINCT S.LOCAL) > 1;

/*listar os eventos com descrições que contenham a palavra "tecnologia"*/
SELECT NOME, DESCRICAO
FROM EVENTO
WHERE LOWER(DESCRICAO) LIKE '%tecnologia%';

/*exibir subeventos que ocorreram fora da cidade do evento principal*/
SELECT E.NOME AS EVENTO, S.NOME AS SUBEVENTO, S.LOCAL AS LOCAL_SUBEVENTO, E.LOCAL AS LOCAL_EVENTO
FROM EVENTO E
JOIN SUBEVENTO S ON E.ID = S.ID_EVENTO
WHERE S.LOCAL <> E.LOCAL;

